### ISSUE TITLE
exercise 0 fails yarn build

### ISSUE THREAD

**Issue by shortwavedave** [TypeFox/theia-workshop#5] opened 2019-07-22 03:36 UTC
using the theia ide to run Exercise 0, it fails to build. Current node version is 10.15.3. I will try a different node version, but wanted to document it.

> gitpod /workspace/theia-workshop $ yarn
> yarn install v1.16.0
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> warning Pattern ["rimraf@latest"] is trying to unpack in the same destination "/home/gitpod/.cache/yarn/v4/npm-rimraf-2.6.2-2ed8150d24a16ea8651e6d6ef0f47c4158ce7a36/node_modules/rimraf" as pattern ["rimraf@^2.6.1","rimraf@^2.2.8","rimraf@^2.2.8","rimraf@^2.2.8","rimraf@^2.6.1","rimraf@^2.6.2","rimraf@2","rimraf@^2.6.2","rimraf@^2.5.4","rimraf@2","rimraf@^2.2.8","rimraf@^2.5.4","rimraf@^2.6.1"]. This could result in non-deterministic behavior, skipping.
> warning Pattern ["@theia/languages@next"] is trying to unpack in the same destination "/home/gitpod/.cache/yarn/v4/npm-@theia-languages-0.4.0-next.e20742c8-d6df31cfb5b648cf2cb0c034687895ab316740a5/node_modules/@theia/languages" as pattern ["@theia/languages@0.4.0-next.e20742c8","@theia/languages@0.4.0-next.e20742c8","@theia/languages@0.4.0-next.e20742c8","@theia/languages@0.4.0-next.e20742c8","@theia/languages@0.4.0-next.e20742c8","@theia/languages@0.4.0-next.e20742c8","@theia/languages@0.4.0-next.e20742c8"]. This could result in non-deterministic behavior, skipping.
> warning vscode-base-languageclient@0.0.1-alpha.5: The engine "vscode" appears to be invalid.
> info fsevents@1.2.4: The platform "linux" is incompatible with this module.
> info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
> [3/4] Linking dependencies...
> warning "workspace-aggregator-5dcbdc4f-3d2d-4a0a-9c75-5752dbf7ec1c > browser-app > @theia/cli > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
> [4/4] Building fresh packages...
> [-/4] ⠠ waiting...
> [2/4] ⠠ electron
> [3/4] ⠠ nsfw
> error /workspace/theia-workshop/node_modules/nsfw: Command failed.
> Exit code: 1
> Command: node-gyp rebuild
> Arguments: 
> Directory: /workspace/theia-workshop/node_modules/nsfw
> Output:
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.7.0
> gyp info using node@10.15.3 | linux | x64
> gyp http GET https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz
> gyp http 200 https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz
> gyp http GET https://nodejs.org/download/release/v10.15.3/SHASUMS256.txt
> gyp http 200 https://nodejs.org/download/release/v10.15.3/SHASUMS256.txt
> gyp info spawn /usr/bin/python
> gyp info spawn args [ '/workspace/theia-workshop/node_modules/node-gyp/gyp/gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   '-f',
> gyp info spawn args   'make',
> gyp info spawn args   '-I',
> gyp info spawn args   '/workspace/theia-workshop/node_modules/nsfw/build/config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/workspace/theia-workshop/node_modules/node-gyp/addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/gitpod/.node-gyp/10.15.3/include/node/common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=/home/gitpod/.node-gyp/10.15.3',
> gyp info spawn args   '-Dnode_gyp_dir=/workspace/theia-workshop/node_modules/node-gyp',
> gyp info spawn args   '-Dnode_lib_file=/home/gitpod/.node-gyp/10.15.3/<(target_arch)/node.lib',
> gyp info spawn args   '-Dmodule_root_dir=/workspace/theia-workshop/node_modules/nsfw',
> gyp info spawn args   '-Dnode_engine=v8',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'build',
> gyp info spawn args   '-Goutput_dir=.' ]
> gyp info spawn make
> gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
> make: Entering directory '/workspace/theia-workshop/node_modules/nsfw/build'
>   CC(target) Release/obj.target/openpa/openpa/src/opa_primitives.o
>   CC(target) Release/obj.target/openpa/openpa/src/opa_queue.o
>   AR(target) Release/obj.target/openpa/openpa.a
>   COPY Release/openpa.a
>   CXX(target) Release/obj.target/nsfw/src/NSFW.o
> make: Leaving directory '/workspace/theia-workshop/node_modules/nsfw/build'
> In file included from ../src/../includes/NSFW.h:5,
>                  from ../src/NSFW.cpp:1:
> ../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
> ../../nan/nan.h:2167:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>      , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
>                                                               ^
> ../src/NSFW.cpp: In static member function ‘static void NSFW::fireErrorCallback(uv_async_t*)’:
> ../src/NSFW.cpp:56:44: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
>    baton->nsfw->mErrorCallback->Call(1, argv);
>                                             ^
> In file included from ../src/../includes/NSFW.h:5,
>                  from ../src/NSFW.cpp:1:
> ../../nan/nan.h:1618:3: note: declared here
>    Call(int argc, v8::Local<v8::Value> argv[]) const {
>    ^~~~
> ../src/NSFW.cpp: In static member function ‘static void NSFW::fireEventCallback(uv_async_t*)’:
> ../src/NSFW.cpp:98:44: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
>    baton->nsfw->mEventCallback->Call(1, argv);
>                                             ^
> In file included from ../src/../includes/NSFW.h:5,
>                  from ../src/NSFW.cpp:1:
> ../../nan/nan.h:1618:3: note: declared here
>    Call(int argc, v8::Local<v8::Value> argv[]) const {
>    ^~~~
> ../src/NSFW.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE NSFW::JSNew(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../src/NSFW.cpp:159:49: error: no matching function for call to ‘v8::Function::NewInstance()’
>      info.GetReturnValue().Set(cons->NewInstance());
>                                                  ^
> In file included from /home/gitpod/.node-gyp/10.15.3/include/node/node.h:63,
>                  from ../../nan/nan.h:51,
>                  from ../src/../includes/NSFW.h:5,
>                  from ../src/NSFW.cpp:1:
> /home/gitpod/.node-gyp/10.15.3/include/node/v8.h:3993:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const’
>    V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
>                                             ^~~~~~~~~~~
> /home/gitpod/.node-gyp/10.15.3/include/node/v8.h:3993:44: note:   candidate expects 3 arguments, 0 provided
> /home/gitpod/.node-gyp/10.15.3/include/node/v8.h:3996:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’
>    V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
>                                             ^~~~~~~~~~~
> /home/gitpod/.node-gyp/10.15.3/include/node/v8.h:3996:44: note:   candidate expects 1 argument, 0 provided
> ../src/NSFW.cpp:176:46: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
>    uint32_t debounceMS = info[0]->Uint32Value();
>                                               ^
> In file included from /home/gitpod/.node-gyp/10.15.3/include/node/v8.h:26,
>                  from /home/gitpod/.node-gyp/10.15.3/include/node/node.h:63,
>                  from ../../nan/nan.h:51,
>                  from ../src/../includes/NSFW.h:5,
>                  from ../src/NSFW.cpp:1:
> /home/gitpod/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
>    V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
>                                                ^~~~~~~~~~~
> /home/gitpod/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
>    declarator __attribute__((deprecated(message)))
>    ^~~~~~~~~~
> ../src/NSFW.cpp:177:54: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
>    v8::String::Utf8Value utf8Value(info[1]->ToString());
>                                                       ^
> In file included from /home/gitpod/.node-gyp/10.15.3/include/node/v8.h:26,
>                  from /home/gitpod/.node-gyp/10.15.3/include/node/node.h:63,
>                  from ../../nan/nan.h:51,
>                  from ../src/../includes/NSFW.h:5,
>                  from ../src/NSFW.cpp:1:
> /home/gitpod/.node-gyp/10.15.3/include/node/v8.h:2892:28: note: declared here
>                    explicit Utf8Value(Local<v8::Value> obj));
>                             ^~~~~~~~~
> /home/gitpod/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
>    declarator __attribute__((deprecated(message)))
>    ^~~~~~~~~~
> ../src/NSFW.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE NSFW::Start(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../src/NSFW.cpp:208:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
>      callback->Call(1, argv);
>                            ^
> In file included from ../src/../includes/NSFW.h:5,
>                  from ../src/NSFW.cpp:1:
> ../../nan/nan.h:1618:3: note: declared here
>    Call(int argc, v8::Local<v8::Value> argv[]) const {
>    ^~~~
> ../src/NSFW.cpp: In member function ‘virtual void NSFW::StartWorker::HandleOKCallback()’:
> ../src/NSFW.cpp:254:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
>      callback->Call(1, argv);
>                            ^
> In file included from ../src/../includes/NSFW.h:5,
>                  from ../src/NSFW.cpp:1:
> ../../nan/nan.h:1618:3: note: declared here
>    Call(int argc, v8::Local<v8::Value> argv[]) const {
>    ^~~~
> ../src/NSFW.cpp:256:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
>      callback->Call(0, NULL);
>                            ^
> In file included from ../src/../includes/NSFW.h:5,
>                  from ../src/NSFW.cpp:1:
> ../../nan/nan.h:1618:3: note: declared here
>    Call(int argc, v8::Local<v8::Value> argv[]) const {
>    ^~~~
> ../src/NSFW.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE NSFW::Stop(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../src/NSFW.cpp:281:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
>      callback->Call(1, argv);
>                            ^
> In file included from ../src/../includes/NSFW.h:5,
>                  from ../src/NSFW.cpp:1:
> ../../nan/nan.h:1618:3: note: declared here
>    Call(int argc, v8::Local<v8::Value> argv[]) const {
>    ^~~~
> ../src/NSFW.cpp: In member function ‘virtual void NSFW::StopWorker::HandleOKCallback()’:
> ../src/NSFW.cpp:321:25: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
>    callback->Call(0, NULL);
>                          ^
> In file included from ../src/../includes/NSFW.h:5,
>                  from ../src/NSFW.cpp:1:
> ../../nan/nan.h:1618:3: note: declared here
>    Call(int argc, v8::Local<v8::Value> argv[]) const {
>    ^~~~
> In file included from ../../nan/nan.h:51,
>                  from ../src/../includes/NSFW.h:5,
>                  from ../src/NSFW.cpp:1:
> ../src/NSFW.cpp: At global scope:
> /home/gitpod/.node-gyp/10.15.3/include/node/node.h:570:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
>        (node::addon_register_func) (regfunc),                          \
>                                            ^
> /home/gitpod/.node-gyp/10.15.3/include/node/node.h:604:3: note: in expansion of macro ‘NODE_MODULE_X’
>    NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
>    ^~~~~~~~~~~~~
> ../src/NSFW.cpp:324:1: note: in expansion of macro ‘NODE_MODULE’
>  NODE_MODULE(nsfw, NSFW::Init)
>  ^~~~~~~~~~~
> In file included from /home/gitpod/.node-gyp/10.15.3/include/node/node.h:63,
>                  from ../../nan/nan.h:51,
>                  from ../src/../includes/NSFW.h:5,
>                  from ../src/NSFW.cpp:1:
> /home/gitpod/.node-gyp/10.15.3/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
> /home/gitpod/.node-gyp/10.15.3/include/node/node_object_wrap.h:85:78:   required from here
> /home/gitpod/.node-gyp/10.15.3/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
>                 reinterpret_cast<Callback>(callback), type);
>                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/gitpod/.node-gyp/10.15.3/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
> ../../nan/nan_object_wrap.h:66:61:   required from here
> /home/gitpod/.node-gyp/10.15.3/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
> make: *** [nsfw.target.mk:128: Release/obj.target/nsfw/src/NSFW.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/workspace/theia-workshop/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
> gyp ERR! System Linux 4.15.0-1028-gcp
> gyp ERR! command "/home/gitpod/.nvm/versions/node/v10.15.3/bin/node" "/workspace/theia-workshop/node_modules/.bin/node-gyp" "rebuild"
> gyp ERR! cwd /workspace/theia-workshop/node_modules/nsfw
> gyp ERR! node -v v10.15.3

**Comment by shortwavedave** [comment] 2019-07-22 03:50
A solution that works is to run the following in the gitpod terminal to change the node version to 8.16:

```
npm install -g n
mkdir ~/.n
```

Add the following lines to ~/.bashrc

```
export N_PREFIX=$HOME/.n
export PATH=$N_PREFIX/bin:$PATH
```

then run

```
source ~/.bashrc
n 8.16.0
```

confirm you got the right version 

> gitpod /workspace/theia-workshop $ node -v
> v8.16.0

Then run yarn

`gitpod /workspace/theia-workshop $ yarn`

If this is an acceptable solution, then I will close this issue - just wanted to document it.

P.S. If you previously ran yarn before changing the node version, you may need to delete the node-gyp build via the command

`rm -r ~/.node-gyp`

**Comment by akosyakov** [comment] 2019-07-29 08:44
@shortwavedave Solutions and exercises were updated? Could you check whether it is alright on your side and close the issue if so.

**Comment by shortwavedave** [comment] 2019-07-29 11:12
It compiled right out of the gate - awesome thanks, looks like you updated the node version. Oddly, solution 3 does not work right away:

![image](https://user-images.githubusercontent.com/22798574/62044114-2f591200-b213-11e9-83dd-7dccf6bedc82.png)

I'm happy to dig into it.

**Comment by chakraborty-slx** [comment] 2019-10-10 12:51
Any solution?, as I am also getting the above problem.


jsonschema-form-widget.tsx:17 Uncaught (in promise) Error: Request 'resolveContent' failed
    at Proxy.<anonymous> (https://3000-e76db07b-a758-449e-98b4-e2f577e55030.ws-eu0.gitpod.io/bundle.js:51286:33)
    at FileResource.<anonymous> (https://3000-e76db07b-a758-449e-98b4-e2f577e55030.ws-eu0.gitpod.io/3.bundle.js:309:62)
    at step (https://3000-e76db07b-a758-449e-98b4-e2f577e55030.ws-eu0.gitpod.io/3.bundle.js:243:23)
    at Object.next (https://3000-e76db07b-a758-449e-98b4-e2f577e55030.ws-eu0.gitpod.io/3.bundle.js:224:53)
    at https://3000-e76db07b-a758-449e-98b4-e2f577e55030.ws-eu0.gitpod.io/3.bundle.js:218:71
    at new Promise (<anonymous>)
    at push.../node_modules/@theia/filesystem/lib/browser/file-resource.js.__awaiter (https://3000-e76db07b-a758-449e-98b4-e2f577e55030.ws-eu0.gitpod.io/3.bundle.js:214:12)
    at FileResource.push.../node_modules/@theia/filesystem/lib/browser/file-resource.js.FileResource.readContents (https://3000-e76db07b-a758-449e-98b4-e2f577e55030.ws-eu0.gitpod.io/3.bundle.js:303:16)
    at new MonacoEditorModel (https://3000-e76db07b-a758-449e-98b4-e2f577e55030.ws-eu0.gitpod.io/13.bundle.js:129:38)
    at MonacoTextModelService.<anonymous> (https://3000-e76db07b-a758-449e-98b4-e2f577e55030.ws-eu0.gitpod.io/13.bundle.js:662:47)
Caused by: Error: 'file:///simple-schema.json' has not been found.

**Comment by akosyakov** [comment] 2019-10-17 11:42
all exercises and solutions should work now, please open a new issue if not

**Closed as completed by akosyakov** 2019-10-17 11:42 UTC
